config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "pages#index" # homepage
  get "/coffee", to: "coffee#index"
  post "/coffee", to: "coffee#create", as: "create_coffee"
  get "/coffee/new", to: "coffee#new"
  get "/coffee/:id/edit", to: "coffee#edit", as: "edit_coffee"  

  get "/coffee/:id", to: "coffee#show", as: "show_coffee"
  put "/coffee/:id", to: "coffee#update", as: "update_coffee"
  delete "/coffee/:id", to: "coffee#destroy"

  # get "/contact", to: "coffee#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee.rb
class Coffee < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/customer_info.rb
class CustomerInfo < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coffee_controller.rb
class CoffeeController < ApplicationController

    before_action :coffee_params, only: [:create, :update]
    before_action :set_coffee, only: [:edit, :show, :destroy]

    def index
        @coffees = Coffee.all
    end

    def show
        
    end

    def new
    end

    def create
        @coffee = Coffee.create(coffee_params)
        redirect_to coffee_path
    end

    def edit
        
    end

    def update
        @coffee.update(coffee_params)
        redirect_to show_coffee_path
    end

    def destroy

        # if @index
        #     @deleted_coffee = @@coffees.delete_at(@index)
        #     render json: @@coffees, status: 200
        # else
        #     render json: { error: "Could not find coffee"}, status: 404
        # end

        @coffee.destroy
        redirect_to coffee_path
    end

    private 

    def coffee_params
        params.require(:coffee).permit(:name, :description, :price)
    end

    def set_coffee
        @coffee = Coffee.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_helper.rb
module CoffeeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/coffee/edit.html.erb
<h1>Edit Coffee</h1>

<form action="<%= update_coffee_path %>" method="POST">

    <input type="hidden" name="_method" value="put">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Name</label>
    <input type="text" name="coffee[name]" value="<%= @coffee["name"] %>">

    <label>Description</label>
    <input type="text" name="coffee[description]" value="<%= @coffee.description %>">

    <label>Price</label>
    <input type="text" name="coffee[price]" value="<%= @coffee.price %>">

    <input type="submit" name="Update Coffee">
</form>

app/views/coffee/index.html.erb
<main id="coffee-index">
    <h1>Welcome to Coder Coffee!</h1>

    <div class="card-container">
        <% @coffees.each do |coffee| %>
            <div class="card">
                <h3><%= coffee[:name] %></h3>
                <p><%= coffee[:description] %></p>
                <p><%= coffee[:price] %></p>
                <%= link_to "See coffee", show_coffee_path(coffee[:id]) %>
            </div>
        <% end %>
    </div>

</main>

app/views/coffee/new.html.erb
<h1>Create a Coffee</h1>
<form action="<%= create_coffee_path %>" method="POST">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Name</label>
    <input type="text" name="coffee[name]">

    <label>Description</label>
    <input type="text" name="coffee[description]">

    <label>Price</label>
    <input type="text" name="coffee[price]">

    <input type="submit" name="Create Coffee">

</form>

app/views/coffee/show.html.erb
<main id="coffee-show">
    <div class="coffee-content">
        <h1> <%= @coffee[:name].capitalize %> </h1>
        <p> <%= @coffee[:description] %> </p>
        <p> Price: <%= @coffee[:price] %> </p>
                
        <%= link_to "Edit Coffee", update_coffee_path(@coffee[:id]) %>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CofeeCafeStudents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome!</h1>